import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors=[]; page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:8000/');
  await page.getByText('Cálculo completado.', {exact:true}).waitFor();
  await page.selectOption('#preset','lamina-disk');
  await page.locator('#expression').click();
  if (!(await page.locator('#expression-editor').isVisible())) throw new Error('No abre el editor');
  await page.locator('#editor-clear').click();
  for (const label of ['1','a/b','π']) await page.getByRole('button',{name:`Insertar ${label}`,exact:true}).click();
  if (await page.locator('#expression-draft').inputValue() !== '1/pi') throw new Error('Entrada de constantes incorrecta');
  if (await page.locator('#editor-preview .katex').count() !== 1) throw new Error('Falta vista matemática');
  await page.locator('#editor-apply').click();
  await page.getByRole('button',{name:/Calcular aproximación/}).click();
  await page.getByText('Cálculo completado.',{exact:true}).waitFor();
  if (await page.locator('#approximation').innerText() !== '1') throw new Error('Masa incorrecta');
  await page.locator('#expression').click(); await page.fill('#expression-draft','sqrt(');
  if (!(await page.locator('#editor-apply').isDisabled())) throw new Error('Permite sintaxis inválida');
  await page.keyboard.press('Escape');
  if (await page.locator('#expression').inputValue() !== '1/pi') throw new Error('Cancelar modificó la expresión');
  await page.locator('#expression').press('Enter');
  await page.fill('#expression-draft','x+1');
  await page.locator('#expression-draft').selectText();
  await page.getByRole('button',{name:'Insertar √',exact:true}).click();
  if (await page.locator('#expression-draft').inputValue() !== 'sqrt(x+1)') throw new Error('Raíz no envuelve la selección');
  await page.screenshot({path:'tmp/expression-editor-mobile.png'});
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Desbordamiento móvil');
  await page.locator('#editor-cancel').click();
  await page.selectOption('#coordinates','polar'); await page.locator('#expression').click();
  if (await page.getByRole('button',{name:'Insertar θ',exact:true}).count() !== 1 || await page.getByRole('button',{name:'Insertar x',exact:true}).count()) throw new Error('Variables incorrectas en polar');
  await page.fill('#expression-draft','theta=2');
  if (!(await page.locator('#editor-apply').isDisabled())) throw new Error('Acepta asignaciones');
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('PASS editor: clic, teclado, π, fracción, masa, raíz, selección, cancelación, validación, polares y móvil.');
} finally { await browser.close(); }
